import {
  STICK_PERCUSSION_SETTINGS,
  STICK_PERCUSSION_TYPES,
} from "../../config/audio.js";

export const PERCUSSION_TYPES = STICK_PERCUSSION_TYPES;
export const PERCUSSION_PROFILES = STICK_PERCUSSION_SETTINGS;
